(ns hive-mcp.events.config
  "Typed config for hive-mcp.events.core via hive-di defconfig.

   Replaces:
     - `defonce *metrics-config (atom default-metrics-config)` (mutable global)
       in hive-mcp.events.core, with two `HIVE_EVENTS_METRICS_*` env-overridable
       fields.
     - 4 raw `(System/getenv \"CLAUDE_SWARM_*\")` calls inside the `:agent-context`
       coeffect, with a typed `EventsAgentConfig`.

   Resolution order (per field): override > env > default.

   Tests can override the resolver via with-redefs:

     (with-redefs [hive-mcp.events.config/metrics-config
                   (fn [] {:max-timings 10 :max-timings-per-type 5})]
       ...)

   Generated by defconfig (per record):
     <Name>             — ADT
     <Name>-fields      — field registry
     <Name>-schema      — Malli schema
     resolve-<Name>     — resolver fn (0/1/2 arity, returns Result)"
  (:require [hive-di.core :refer [defconfig env]]
            [hive-dsl.result :as r]))
;; Copyright (C) 2026 Pedro Gomes Branquinho (BuddhiLW) <pedrogbranquinho@gmail.com>
;;
;; SPDX-License-Identifier: AGPL-3.0-or-later

;; =============================================================================
;; EventsMetricsConfig — bounded-buffer caps for the :metrics interceptor
;; =============================================================================

(defconfig EventsMetricsConfig
  :max-timings          (env "HIVE_EVENTS_METRICS_MAX_TIMINGS"
                             :default 1000
                             :type :int
                             :doc "Max samples in the global :timings buffer (FIFO eviction)")
  :max-timings-per-type (env "HIVE_EVENTS_METRICS_MAX_TIMINGS_PER_TYPE"
                             :default 200
                             :type :int
                             :doc "Max samples per event-type in :timings-by-type (FIFO eviction)"))

;; =============================================================================
;; EventsAgentConfig — swarm agent context env (consumed by :agent-context cofx)
;; =============================================================================

(defconfig EventsAgentConfig
  :agent-id  (env "CLAUDE_SWARM_SLAVE_ID"
                  :type :string
                  :required false
                  :doc "Current swarm agent (ling) id; nil for coordinator/root")
  :parent-id (env "CLAUDE_SWARM_PARENT_ID"
                  :type :string
                  :required false
                  :doc "Parent agent id when spawned by another agent")
  :depth     (env "CLAUDE_SWARM_DEPTH"
                  :type :int
                  :required false
                  :doc "Swarm spawn depth (0 = root). Coerced to int.")
  :role      (env "CLAUDE_SWARM_ROLE"
                  :type :string
                  :required false
                  :doc "Agent role label (e.g. ling, coordinator)"))

;; =============================================================================
;; Resolver helpers — pure surface used by events/core.clj
;; =============================================================================

(defn- resolve-or-throw
  "Resolve a defconfig record into a plain map. Throws on resolution failure
   (defaults guarantee resolution under normal conditions for these configs)."
  [resolver overrides]
  (let [result (resolver overrides)]
    (if (r/ok? result)
      (:ok result)
      (throw (ex-info "events/config resolution failed"
                      {:result result :overrides overrides})))))

;; Runtime override layer for backwards compatibility with `configure-metrics!`.
;; Not the primary path — tests should prefer `with-redefs` on `metrics-config`.
;; Keys present here override the resolver result on every call.
(defonce ^:private *metrics-overrides (atom {}))

(defn set-metrics-override!
  "Merge runtime overrides into the metrics-config layer.
   Used by `hive-mcp.events.core/configure-metrics!` for back-compat."
  [m]
  (swap! *metrics-overrides merge m))

(defn clear-metrics-overrides!
  "Drop all runtime overrides set via `set-metrics-override!`. For testing."
  []
  (reset! *metrics-overrides {}))

(defn metrics-config
  "Resolved EventsMetricsConfig as a plain map.

   Resolution: defconfig (defaults + env) <- runtime overrides <- caller overrides.

   Tests can rebind via `with-redefs`:
     (with-redefs [metrics-config (constantly {:max-timings 5 :max-timings-per-type 3})]
       ...)"
  ([] (metrics-config {}))
  ([overrides]
   (let [base (resolve-or-throw resolve-EventsMetricsConfig {})]
     (merge base @*metrics-overrides overrides))))

(defn agent-config
  "Resolved EventsAgentConfig as a plain map.

   Tests can rebind via `with-redefs`:
     (with-redefs [agent-config (constantly {:agent-id \"test\" :parent-id nil
                                             :depth nil :role nil})]
       ...)"
  ([] (agent-config {}))
  ([overrides]
   (resolve-or-throw resolve-EventsAgentConfig overrides)))