;; Copyright (C) 2026 Pedro Gomes Branquinho (BuddhiLW) <pedrogbranquinho@gmail.com>
;;
;; SPDX-License-Identifier: AGPL-3.0-or-later

(ns hive-mcp.events.handlers.saa-config
  "Typed config for SAA (Silence-Abstract-Act) workflow event handlers,
   resolved via hive-di defconfig.

   Replaces ad-hoc `(System/getenv \"CLAUDE_SWARM_SLAVE_ID\")` reads scattered
   across the four SAA event handlers (handle-saa-started,
   handle-saa-phase-complete, handle-saa-completed, handle-saa-failed) with
   a single declarative config surface.

   Resolution per field (highest precedence first):
     1. Explicit override map (caller passes the key)
     2. Environment variable lookup (e.g. CLAUDE_SWARM_SLAVE_ID)
     3. ~/.config/hive-mcp/config.edn at [:services :saa <key>]
     4. Hardcoded default (\"unknown-agent\")

   Generated by defconfig:
     SAAHandlerConfig          — ADT (:config/resolved | :unresolved | :invalid)
     SAAHandlerConfig-fields   — field registry (source of truth)
     SAAHandlerConfig-schema   — Malli closed map schema
     resolve-SAAHandlerConfig  — resolver fn (0/1/2 arity, returns Result)

   Public helper:
     effective-agent-id        — coalesce caller-provided id > config-resolved id"
  (:require [hive-di.core :as di]
            [hive-di.source :as src]
            [hive-dsl.result :as r]
            [hive-mcp.config.path :as config-path]))

(def config-edn-path
  "Canonical hive-mcp config file. Each field's :file source reads from here."
  config-path/config-path)

(def ^:const default-agent-id
  "Sentinel agent identifier when no swarm slave id is configured.
   Surfaces in logs/shouts so operators can spot misconfigured agents."
  "unknown-agent")

(di/defconfig SAAHandlerConfig
  :slave-agent-id (src/coalesce
                    [(src/env "CLAUDE_SWARM_SLAVE_ID" :required false)
                     (src/file config-edn-path
                               [:services :saa :slave-agent-id]
                               :required false)]
                    :default default-agent-id
                    :type :string
                    :doc "SAA workflow agent identifier. Env: CLAUDE_SWARM_SLAVE_ID. config.edn: [:services :saa :slave-agent-id]. Default: \"unknown-agent\". Used as fallback when an event payload omits :agent-id."))

(defn resolve!
  "Resolve SAAHandlerConfig with optional overrides.
   Returns the resolved map directly. Throws on resolution failure
   (defaults guarantee resolution under normal conditions)."
  ([] (resolve! {}))
  ([overrides]
   (let [result (resolve-SAAHandlerConfig overrides)]
     (if (r/ok? result)
       (:ok result)
       (throw (ex-info "SAAHandlerConfig resolution failed"
                       {:result result :overrides overrides}))))))

(defn slave-agent-id
  "Resolved CLAUDE_SWARM_SLAVE_ID (or config.edn / default).
   Always returns a non-blank string."
  []
  (:slave-agent-id (resolve!)))

(defn effective-agent-id
  "Coalesce caller-provided agent-id with the resolved slave-agent-id.
   Used by SAA event handlers to derive the broadcast id when an event
   payload omits :agent-id."
  [agent-id]
  (or agent-id (slave-agent-id)))
